# Generated by Django 5.1.4 on 2024-12-16 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("romans", "로맨스"),
                            ("fantasy", "판타지"),
                            ("thriller", "스릴러"),
                            ("mystery", "미스터리"),
                            ("comic", "코믹"),
                            ("diary", "하루일기"),
                        ],
                        max_length=10,
                        verbose_name="카테고리",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="제목")),
                ("content", models.TextField(verbose_name="본문")),
                (
                    "create_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="작성일자"),
                ),
                (
                    "update_at",
                    models.DateTimeField(auto_now=True, verbose_name="작성일자"),
                ),
            ],
        ),
    ]
