# Generated by Django 5.1.4 on 2024-12-16 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blog",
            old_name="create_at",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="blog",
            old_name="update_at",
            new_name="updated_at",
        ),
    ]
